import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/components/us/Header";
import { Footer } from "@/components/us/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-black">
        <Header />
        <main className="min-h-screen pt-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
